name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHub Token
          token: ${{ secrets.metrics }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_followup: yes
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills
          plugin_leetcode_user:
            type: string
            description: |
              LeetCode login
            default: MrLu
            preset: no
